# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nicholas McDonald
email: nmmcdona@ucsd.edu
description: > # this means to ignore newlines until "baseurl:"
  This is my personal blog website that I hopefully will be able to contribute to frequently.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nmcdonaldd.github.io" # the base hostname & protocol for your site
twitter_username: nickmcd19
github_username:  nmcdonaldd

# Build settings
markdown: kramdown
